name: 'Push a directory to another repository'
description: 'Used for pushing a copy of a folder to another repository'
inputs:
  source_folder:
    description: 'Source folder from the origin directory'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Directory to push the folder contents to'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push folder to, defaults to master'
    required: false
  commit_msg:
    description: 'The commit message'
    required: false
  destination_branch_create:
    description: 'Destination branch to create for this commit'
    required: false
  target_username:
    description: 'Target username'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target_username }}
    - ${{ inputs.source-file }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.destination-branch-create }}
    - ${{ inputs.commit_msg }}
branding:
  icon: 'git-commit'
  color: 'green'
